CREATE TYPE developer_languages AS ENUM ('JAVA','JAVASCRIPT','TYPESCRIPT','PYTHON','C','CPLUSPLUS','CSHARP','PHP','RUBY','SWIFT','KOTLIN','GO','RUST','SCALA','ZIG','R','DART','LUA','HASKELL','ELIXIR','CLOJURE','SHELL','SQL','HTML', 'CSS');

ALTER TABLE tb_developer DROP COLUMN IF EXISTS languages;

