
    create table tb_developer (
        seniority smallint check (seniority between 0 and 7),
        years_experiente integer not null,
        id uuid not null,
        especialization varchar(255) check (especialization in ('FRONTEND','BACKEND','FULLSTACK','MOBILE','DEVOPS','CLOUD_ENGINEERING','DATA_SCIENCE','MACHINE_LEARNING','EMBEDDED_SYSTEMS','SECURITY','GAME_DEVELOPMENT','DATABASE_ADMINISTRATOR','QA_TESTING','UI_UX_DESIGN','BLOCKCHAIN','OTHER')),
        github varchar(255),
        linkedin varchar(255),
        name varchar(255),
        languages bytea,
        primary key (id)
    );

    create table tb_tasks (
        due_date date,
        language smallint check (language between 0 and 24),
        id bigint generated by default as identity,
        developer_id uuid,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists tb_tasks 
       add constraint FK499xpg4xnw2766b5vsglvrteq 
       foreign key (developer_id) 
       references tb_developer;

    create table tb_developer (
        seniority smallint check (seniority between 0 and 7),
        years_experiente integer not null,
        id uuid not null,
        especialization varchar(255) check (especialization in ('FRONTEND','BACKEND','FULLSTACK','MOBILE','DEVOPS','CLOUD_ENGINEERING','DATA_SCIENCE','MACHINE_LEARNING','EMBEDDED_SYSTEMS','SECURITY','GAME_DEVELOPMENT','DATABASE_ADMINISTRATOR','QA_TESTING','UI_UX_DESIGN','BLOCKCHAIN','OTHER')),
        github varchar(255),
        linkedin varchar(255),
        name varchar(255),
        languages bytea,
        primary key (id)
    );

    create table tb_tasks (
        due_date date,
        language smallint check (language between 0 and 24),
        id bigint generated by default as identity,
        developer_id uuid,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists tb_tasks 
       add constraint FK499xpg4xnw2766b5vsglvrteq 
       foreign key (developer_id) 
       references tb_developer;
