
    create table tb_developer (
        seniority smallint check (seniority between 0 and 7),
        specialization smallint check (specialization between 0 and 15),
        years_experiente integer not null,
        id uuid not null,
        github varchar(255),
        linkedin varchar(255),
        name varchar(255),
        languages bytea,
        primary key (id)
    );

    create table tb_tasks (
        due_date date,
        language smallint check (language between 0 and 24),
        id bigint generated by default as identity,
        developer_id uuid,
        description varchar(255),
        name varchar(255),
        primary key (id)
    );

    alter table if exists tb_tasks 
       add constraint FK499xpg4xnw2766b5vsglvrteq 
       foreign key (developer_id) 
       references tb_developer;
